# Calculating the average consumption intensity factor for Swedish households

In [3]:
import pymrio
import pandas as pd
import numpy as np

In [ ]:
#exio3 = pymrio.parse_exiobase3('/Users/rafa/Box/Python/EXIOBASE/IOT_2011_pxp')

In [2]:
exio3 = pymrio.parse_exiobase3('/Users/rafa/Downloads/IOT_2011_pxp')

In [4]:
exio3.calc_all()

In [8]:
cf = pd.read_csv('/Users/rafa/Box/Python/Cha_Fac_footprints_RL.csv',';', header=[0], index_col = [0])
cf

,Taxes less subsidies on products purchased: Total,Other net taxes on production,"Compensation of employees; wages, salaries, & employers social contributions: Low-skilled","Compensation of employees; wages, salaries, & employers social contributions: Medium-skilled","Compensation of employees; wages, salaries, & employers social contributions: High-skilled",Operating surplus: Consumption of fixed capital,Operating surplus: Rents on land,Operating surplus: Royalties on resources,Operating surplus: Remaining net operating surplus,Employment: Low-skilled male,...,Water Withdrawal Blue - Electricity - once-through - Electricity by hydro,Water Withdrawal Blue - Electricity - once-through - Electricity by wind,Water Withdrawal Blue - Electricity - once-through - Electricity by petroleum and other oil derivatives,Water Withdrawal Blue - Electricity - once-through - Electricity by biomass and waste,Water Withdrawal Blue - Electricity - once-through - Electricity by solar photovoltaic,Water Withdrawal Blue - Electricity - once-through - Electricity by solar thermal,"Water Withdrawal Blue - Electricity - once-through - Electricity by tide, wave, ocean",Water Withdrawal Blue - Electricity - once-through - Electricity by Geothermal,Water Withdrawal Blue - Electricity - once-through - Electricity nec,Water Withdrawal Blue - Domestic - domestic Water Withdrawal Blue
Carbon Footprint [kg CO2-eq.],0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Land footprint [km2],0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Material footprint [kt],0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Water footprint [Mm3],0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Energy footprint [TJ],0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [46]:
# Consumption matrix
#M.EUR
Y = exio3.Y.SE.groupby(level=1, sort=False).sum()[['Final consumption expenditure by households']]
Y

category                                           Final consumption expenditure by households
sector
Paddy rice                                                                            0.123462
Wheat                                                                               246.195003
Cereal grains nec                                                                    33.096102
Vegetables, fruit, nuts                                                            1394.192773
Oil seeds                                                                           259.320041
...                                                                                        ...
Membership organisation services n.e.c. (91)                                          1.551583
Recreational, cultural and sporting services (92)                                  6476.957006
Other services (93)                                                                3076.329140
Private households with employed persons (95)                                        71.089902
Extra-territorial organizations and bodies                                            0.000000

[200 rows x 1 columns]

In [72]:
# Multiply the matrix comsumption-based accounting by the cf (I'm doing it only for CO2eq.)
# You can use Richad Wood's file

# Impact of total comsumption per category
# Impact per M.EUR (total consumption)

cba_SE = exio3.satellite.D_cba.SE.T.dot(cf.T)[['Carbon Footprint [kg CO2-eq.]']]
cba_SE

                                                   Carbon Footprint [kg CO2-eq.]
sector
Paddy rice                                                          4.300361e+05
Wheat                                                               2.708281e+08
Cereal grains nec                                                   3.951627e+07
Vegetables, fruit, nuts                                             7.062354e+08
Oil seeds                                                           1.847766e+08
...                                                                          ...
Membership organisation services n.e.c. (91)                        2.102769e+09
Recreational, cultural and sporting services (92)                   1.079669e+09
Other services (93)                                                 3.994310e+08
Private households with employed persons (95)                       1.106690e+06
Extra-territorial organizations and bodies                          0.000000e+00

[200 rows x 1 columns]

In [77]:
# Divide the matrix total consumption (Y) by the matrix impact of total consumption (cba_SE) to find the consumption intensity factors

# CO2 per M.EUR

co2_per_ME = cba_SE[['Carbon Footprint [kg CO2-eq.]']].div(Y['Final consumption expenditure by households'], axis=0)
co2_per_ME

                                                   Carbon Footprint [kg CO2-eq.]
sector
Paddy rice                                                          3.483137e+06
Wheat                                                               1.100055e+06
Cereal grains nec                                                   1.193986e+06
Vegetables, fruit, nuts                                             5.065550e+05
Oil seeds                                                           7.125428e+05
...                                                                          ...
Membership organisation services n.e.c. (91)                        1.355242e+09
Recreational, cultural and sporting services (92)                   1.666938e+05
Other services (93)                                                 1.298401e+05
Private households with employed persons (95)                       1.556747e+04
Extra-territorial organizations and bodies                                   NaN

[200 rows x 1 columns]

In [83]:
# Merging the two matrices
multi = Y.merge(co2_per_ME, on='sector')
multi

,Final consumption expenditure by households,Carbon Footprint [kg CO2-eq.]
sector,,
Paddy rice,0.123462,3.483137e+06
Wheat,246.195003,1.100055e+06
Cereal grains nec,33.096102,1.193986e+06
"Vegetables, fruit, nuts",1394.192773,5.065550e+05
Oil seeds,259.320041,7.125428e+05
...,...,...
Membership organisation services n.e.c. (91),1.551583,1.355242e+09
"Recreational, cultural and sporting services (92)",6476.957006,1.666938e+05
Other services (93),3076.329140,1.298401e+05
Private households with employed persons (95),71.089902,1.556747e+04
Extra-territorial organizations and bodies,0.000000,NaN

In [86]:
#import numpy as np
#np.average(multi["Carbon Footprint [kg CO2-eq.]"], weights=multi["Final consumption expenditure by households"])

nan

In [89]:
# canculating the weighted average
#(df["quantity"] * df["weight"]).sum() / df["weight"].sum()
# kg per euros
wavg_kg_EUR = (multi["Carbon Footprint [kg CO2-eq.]"]*multi["Final consumption expenditure by households"]).sum()/multi["Final consumption expenditure by households"].sum()/1000000
wavg_kg_EUR

0.5487565443466703

In [94]:
#alternatevely
(co2_per_ME["Carbon Footprint [kg CO2-eq.]"]*Y["Final consumption expenditure by households"]).sum()/Y["Final consumption expenditure by households"].sum()/1000000

0.5487565443466703

In [92]:
# g per SEK
#still need to ajust for inflation
wavg_g_SEK = wavg_kg_EUR*100
wavg_g_SEK

54.875654434667034